name: sample-test
log: debug
timeout: 300
interval: 60
slack_urls:
  - https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYYY/XXXXXXX
targets:
  - url: example.com
    port: 443
    method: GET
    timeout: 5
  - url: example-internal.com
    port: 8090
    method: GET
    timeout: 5
    internal: true
    regions:
      - ap-northeast-2
      - ap-northeast-1

# Region configurations
regions:
  - region: ap-northeast-1
  - region: ap-southeast-1
  - region: ap-southeast-2
  - region: ap-northeast-2
    subnets:
      - subnet-xxxx
      - subnet-yyyy
      - subnet-zzzz
    security_groups:
      - sg-xxxx
  - region: ap-south-1
  - region: eu-north-1
  - region: eu-west-3
  - region: eu-west-2
  - region: eu-west-1
  - region: sa-east-1
  - region: af-south-1
  - region: ca-central-1
  - region: eu-central-1
  - region: us-east-1
  - region: us-east-2
  - region: us-west-1
  - region: us-west-2
