name: sample-template
log: debug
timeout: 300
interval: 300
slack_urls:
  - https://hooks.slack.com/services/XXXXXXX/YYYYYYY
targets:
  - url: https://weverse.io
    method: GET
  - url: https://www.amazon.com
    method: GET
  - url: https://www.facebook.com
    method: GET

# Region configurations
regions:
  - region: ap-northeast-2
  - region: ap-south-1
  - region: eu-north-1
  - region: eu-west-3
  - region: eu-west-2
  - region: eu-west-1
  - region: ap-northeast-1
  - region: sa-east-1
  - region: ca-central-1
  - region: ap-southeast-1
  - region: ap-southeast-2
  - region: eu-central-1
  - region: us-east-1
  - region: us-east-2
  - region: us-west-1
  - region: us-west-2
